apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml

namespace: instavote

images:
- name: schoolofdevops/vote
  newTag: v4

commonAnnotations:
  supported-by: "sre@example.com"

configMapGenerator:
  - name: vote-options
    envs:
      - options.env
